# version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: ["./.env"]
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./.env:/.env:ro
    ports:
      - "5432:5432"          # only accessible inside LAN
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U its_user -d inventory_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    develop:
      watch:
        - action: restart
          path: ./.env
          target: /.env

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    restart: unless-stopped
    env_file: ["./.env"]
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npm run migrate && npm run seed && exec npm run dev"
    volumes:
      - ./server:/server
      - /server/node_modules
      - ./.env:/.env:ro
    develop:
      watch:
        - action: restart
          path: ./.env
          target: /.env
        - action: rebuild
          path: ./server
          target: /server
          ignore:
            - node_modules/
            - dist/

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: ["./.env"]
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
      - ./.env:/.env:ro
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    develop:
      watch:
        - action: restart
          path: ./.env
          target: /.env
        - action: rebuild
          path: ./client
          target: /app
          ignore:
            - node_modules/
            - dist/


volumes:
  pg_data:
